language: java
dist: bionic
sudo: required
notifications:
  # Email notifications are disabled to not annoy anybody.
  email: false 
# Run SonarQube on code
addons:
  sonarqube:
    token:
      secure: c11f78b32f6c5a83c760c5b6d6ea388e166b07f7 # encrypted value of your token
script:
  - ant download-deps
  - ant
  - ant test
  - sonar-scanner
