# -----------------------------------------
# Signal processing processors (!)
# -----------------------------------------

<eml_expr>               := <sig_peak> | <sig_plateau> | <sig_thresh> ;
<sig_peak>               := THE PEAK OF <processor> ;
<sig_plateau>            := THE PLATEAU OF <processor> ) ;
<sig_thresh>             := ( <processor> ) THRESHOLD <number> ;
